spring.security.member.name=member
spring.security.member.password=1234
spring.datasource.username=tester
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=create-drop
#custom.fileDirPath=/usr/file
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
