spring.application.name=Omok
spring.profiles.active=dev
spring.profiles.include=secret
spring.datasource.url=jdbc:mysql://localhost:3306/Omok
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.propertie.hibernate.show_sql=true
spring.jpa.propertie.hibernate.format_sql=true
spring.jpa.propertie.hibernate.use_sql_comments=true
spring.logging.level.root=INFO
# ?? ?? ??? INFO? ?????.
# ?? ?????? ??? ?? ?? ?? ??? ?? ???(?: ??, ?? ?)? ????? ???.

spring.logging.level.com.example.sksb=DEBUG 
# com.example.sksb ???? ?? ?? ??? DEBUG? ?????.
# ? ??? ?? ?? ?? ???? ?? ??? ??? ??? ??? ?????.
# ????? ?? ?? ??? ?? ? ?????.

spring.logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Hibernate? JDBC ??? ?? ?? ??? TRACE? ?????.
# ? ??? SQL ??? ?? ?? ??? ??? ?? ???? ?????.
# ???????? ????? ????? ??? ? ?????

spring.logging.level.org.hibernate.orm.jdbc.extract=TRACE
# Hibernate? JDBC ?? ?? ?? ??? TRACE? ?????.
# ? ??? ???????? ??? ???? ??? ?? ??? ??? ?????.
# ?? ??? ???? ??? ?? ?? ????? ? ? ??? ???
